name 'elk_stack'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures elk_stack'
long_description 'Installs/Configures elk_stack'
version '2.1.2'
