---
driver:
  name: docker
  binary: docker.io
  use_sudo: false
  privileged: true

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: centos-6.8
  - name: centos-7.2

suites:
  - name: dev
    driver:
      run_command: /usr/sbin/init
    run_list:
      - recipe[webserver::default]
    attributes: { 'java': { 'jdk_version': '7' } }
    driver_config:
      forward:
        - 8080:80
    excludes: centos-6.8
  - name: qa
    driver:
      run_command: /sbin/init
    run_list:
      - recipe[webserver::default]
    attributes: { 'java': { 'jdk_version': '6' } }
    driver_config:
      forward:
        - 8080:80
    includes: centos-6.8
