name 'webserver'
maintainer 'Govindarajan V'
maintainer_email 'govindarajanv@gmail.com'
license 'all_rights'
description 'Installs/Configures webserver'
long_description 'Installs/Configures webserver'
version '1.3.1'
