name 'ci_server'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures ci_server'
long_description 'Installs/Configures ci_server'
version '2.0.3'
