name 'my_java'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures my_java'
long_description 'Installs/Configures my_java'
version '0.1.0'
