name 'sample_ps'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures sample_ps'
long_description 'Installs/Configures sample_ps'
version '0.1.0'
